# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Spark for R&D 
email: 
description: > # this means to ignore newlines until "baseurl:"
  This is a blog about applications of Spark for research and development by various authors, covering use cases of their respective fields and applications.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username:
github_username:
exclude: [README.md, spark_start.sh, Rakefile, notebooks/.ipynb_checkpoints]

# Build settings
markdown: kramdown
